name: Go
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.14.X
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: make install

      - name: Build
        run: make build

      - name: Test
        run: make tests

      - name: Check Coverage
        run: |
          set -e
          echo "" > coverage.txt
          for d in $(go list ./... | grep -v vendor); do
            go test -race -coverprofile=profile.out -covermode=atomic $d
            if [ -f profile.out ]; then
              cat profile.out >> coverage.txt
              rm profile.out
            fi
          done
          bash <(curl -s https://codecov.io/bash)
